---
title: "R Notebook"
output: html_notebook
---

# Install

> package depends on R `magick` which might need OS util `sudo apt install libmagick++-dev`

```{r eval=FALSE}
## install.packages("devtools") # if not already installed on your system
devtools::install_github("munichrocker/DatawRappr")
```

```{r}
library(DatawRappr)
```

# Auth

## run ~~once~~

> add `API_KEY="key_value"` to the project's `.Renviron` (i.e. with `usethis::edit_r_environ("project")`)

```{r}
datawrapper_auth(api_key = Sys.getenv("API_KEY"), overwrite = TRUE)
```

## Test Auth

> needs scope: read user info

```{r}
test_key <- dw_test_key()
stopifnot(test_key$response$status_code == 200)
```

# Publish

## get all charts

> there seems to be a bug or so

```{r eval=FALSE}
charts <- DatawRappr::dw_list_charts(api_key = "environment", published = TRUE)
```

```{r}
charts <- c(
  "z9ijf", "UVyA7", "8h04B", "BO1V2", # tables
  # barcharts
  "k1ftC", #"4b4W8", # Ostbahnhof
  "Z61P0","sJvtl" 
  )
```

```{r}
# charts <- c("4b4W8") # Ostbahnhof Playground
```

```{r}
result <- purrr::walk(charts, dw_publish_chart, return_urls = FALSE)
```
